version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only
  ignore:
  - dependency-name: paper_trail
    versions:
    - 12.0.0
  - dependency-name: rails
    versions:
    - 6.0.3.5
