pull_request_rules:
  - name: automatic merge for master when reviewed and CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=ready-to-merge
    actions:
        merge:
          strict: true
          method: squash
  - name: automatic merge for updates when CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=dependencies
    actions:
        merge:
          strict: true
          method: squash
  - name: delete head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
        comment:
          message: This pull request has conflict. Could you fix it @{{author}}?
