queue_rules:
  - name: default
    merge_conditions:
      - check-success=Build

pull_request_rules:
  - name: automatic merge for master when reviewed and CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=ready-to-merge
    actions:
      queue:
        name: default
        method: squash
  - name: automatic merge for updates when CI passes
    conditions:
      - "#approved-reviews-by>=1"
      - base=master
      - label=dependencies
    actions:
      queue:
        name: default
        method: squash
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: This pull request has conflict. Could you fix it @{{author}}?
