require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - config/initializers/*
    - test/**/*
    - 'vendor/**/*'
ClassLength:
  Max: 150
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 35
Style/HashEachMethods:
  Enabled: true
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Documentation:
  Enabled: false
