require: rubocop-rails

AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - config/initializers/*
    - test/**/*
    - 'vendor/**/*'
ClassLength:
  Max: 150
Layout/LineLength:
  Max: 120
Metrics/BlockLength:
  Max: 35
# Disable AmbiguousBlockAssociation since it is causing a bunch of irrelevant errors on
# rubocop 0.48.1, this can be re-enabled once we are on a newer version of rubocop
Documentation:
  Enabled: false
