AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - config/initializers/*
    - test/**/*
    - 'vendor/**/*'
Rails:
  Enabled: true
ClassLength:
  Max: 150
Metrics/LineLength:
  Max: 120
# Disable AmbiguousBlockAssociation since it is causing a bunch of irrelevant errors on
# rubocop 0.48.1, this can be re-enabled once we are on a newer version of rubocop
Documentation:
  Enabled: false
