version: '3.5'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - scoreboard_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    expose:
      - "5432"
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/registration_development
      RAILS_ENV: development
    env_file: .env-prod
    restart: unless-stopped
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - "db"

volumes:
  scoreboard_data:
