version: '3.5'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - scoreboard_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: registration_production
    expose:
      - "5432"
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/registration_production
      RAILS_ENV: production
    restart: unless-stopped
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/
      - ./nginx/certs/:/etc/nginx/cert/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "web"

volumes:
  scoreboard_data:
