version: '3'
services:
  db:
    image: "postgres" # use latest official postgres version
    volumes:
        - db_data:/var/lib/postgresql/data
    env_file: .env
    expose:
    - "5432"
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/registration_development
      RAILS_SERVE_STATIC_FILES: "true"
      RAILS_ENV: development
      DISABLE_SPRING: "true"
    env_file: .env-prod
    restart: unless-stopped
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    depends_on:
      - "db"

volumes:
  db_data: