version: '3.5'

services:
  db:
    image: postgres:12
    restart: unless-stopped
    volumes:
      - scoreboard_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: scoreboard_production
    expose:
      - "5432"
  web:
    image: mitrectf/ctf-scoreboard:latest
    environment:
      DATABASE_URL: postgres://postgres:${POSTGRES_PASSWORD}@db/scoreboard_production
    env_file: .env-prod
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - "db"
  nginx:
    image: nginx:latest
    container_name: production_nginx
    environment:
      NGINX_HOST: ${NGINX_HOST}
    volumes:
      - ./nginx/conf:/etc/nginx/templates
      - ./nginx/certs:/etc/nginx/cert/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - "web"

volumes:
  scoreboard_data:
