# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: registration_development
  url: postgres://postgres:${POSTGRES_PASSWORD}@db/registration_development

test:
  <<: *default
  database: registration_test

production:
  <<: *default
  database: registration_production
  url: <%= ENV['DATABASE_URL'] %>