name: Auto approve Dependabot PRs
on:
  pull_request_target:
    types: [labeled]

jobs:
  approve:
    name: Auto-approve dependabot PRs
    if: github.event.pull_request.user.login == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'dependencies')
    runs-on: ubuntu-20.04
    steps:
    - uses: hmarr/auto-approve-action@v2
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
